title: Turku in a nutshell
author: Raúl Medina
email: lavierulis@gmail.com
theme: minima

description: > # this means to ignore newlines until "baseurl:"
  Here you will read a bad english attempt to describe what is living in Turku, Finland as Mexican.
  More than an informative blog, this is my point of view, it's how a 26 years old Mexican from the north experiences the life.
  
# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RulisM # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
