title: Turku in a nutshell
author: Raúl Medina
email: lavierulis@gmail.com
theme:  jekyll-theme-minimal

description: > # this means to ignore newlines until "baseurl:"
  Here you will read a bad english attempt to describe what is living in Turku, Finland as Mexican.
  More than an informative blog, this is my point of view, it's how a 26 years old Mexican from the north experiences the life.
  
# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RulisM # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


title: Tu título genial
author: Usuario GitHub
email: tu-nombre@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Escribe una descripción estupenda para tu nuevo sitio aquí. Puedes editar esta línea
  en _config.yml. Aparecerá en los metadatos de cabecera de tu documento (para los 
  resultados de búsqueda de Google) y en la descripción del sitio de tu archivo feed.xml.

# social links
twitter_username: tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  tu-usuario-github # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
theme: minima
