# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Travel stories
author: Raul Medina
email: salasraul96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Join me in coming back to my best (some bad) times far from my Juaritos querido.
 
#baseurl: "/travelblog"

# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RaulM6 # DO NOT include the @ character, or else the build will fail!
# logo: /me.png

show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
#markdown: kramdown
theme: jekyll-theme-minimal
#thene: minima
#plugins:
   jekyll-feed
