title: Travel blog
author: Raul Medina
![My helpful screenshot](/_imgs/Turku.jgp)
#email: salasraul96@gmail.com
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
 Join me in coming back to my best (some bad) times far from my Juaritos querido.


# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RaulM6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
