title: Travel blog
author: Raul Medina
email: salasraul96@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Here you will read a bad english attempt to describe what is living (in turku so far) and traveling as a Mexican.
 More than an informative blog, this is my point of view, it's how a 26 years old Mexican from the north where the temperature goes up to 38°C experience the life 


# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RaulM6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
