title: Travel blog
author: Raul Medina
logo: /me.jgp
email: salasraul96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Join me in coming back to my best (some bad) times far from my Juaritos querido.
 
baseurl: "/travelblog"

# social links
twitter_username: RaulMed656 # DO NOT include the @ character, or else the build will fail!
github_username:  RaulM6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
